#!/usr/bin/env bash
set -euo pipefail

private_key="${TAURI_SIGNING_PRIVATE_KEY:-}"

if [[ -n "${TAURI_SIGNING_PRIVATE_KEY_B64:-}" ]]; then
  if ! private_key="$(printf '%s' "$TAURI_SIGNING_PRIVATE_KEY_B64" | base64 --decode 2>/dev/null)"; then
    echo "::error::TAURI_SIGNING_PRIVATE_KEY_B64 is not valid base64."
    exit 1
  fi
fi

if [[ -z "$private_key" ]]; then
  echo "::error::TAURI_SIGNING_PRIVATE_KEY is not set. Set TAURI_SIGNING_PRIVATE_KEY to the full private key text, or set TAURI_SIGNING_PRIVATE_KEY_B64 to its base64-encoded content."
  exit 1
fi

if [[ "$private_key" == *"minisign public key"* ]]; then
  echo "::error::TAURI_SIGNING_PRIVATE_KEY contains a public key. Use the private key file generated by Tauri signer, not the .pub file."
  exit 1
fi

if [[ "$private_key" != *"untrusted comment:"* ]]; then
  echo "::error::TAURI_SIGNING_PRIVATE_KEY must be the full private key text generated by Tauri signer, including the 'untrusted comment:' line."
  exit 1
fi

{
  echo 'TAURI_SIGNING_PRIVATE_KEY<<__TAURI_SIGNING_PRIVATE_KEY__'
  printf '%s\n' "$private_key"
  echo '__TAURI_SIGNING_PRIVATE_KEY__'
} >> "$GITHUB_ENV"
